/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g4s21e4bfrb;

import Preguntas.Resultado;

/**
 *
 * @author Brayan Rodriguez
 */
public class JF2 extends javax.swing.JFrame {

    /**
     * Creates new form JF2
     */
    public JF2() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg2 = new javax.swing.ButtonGroup();
        rb1p2 = new javax.swing.JRadioButton();
        rb2p2 = new javax.swing.JRadioButton();
        rb3p2 = new javax.swing.JRadioButton();
        rb4p2 = new javax.swing.JRadioButton();
        btnregresar2 = new javax.swing.JButton();
        btnsiguiente2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg2.add(rb1p2);
        rb1p2.setText("282");
        rb1p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1p2ActionPerformed(evt);
            }
        });

        bg2.add(rb2p2);
        rb2p2.setText("562");

        bg2.add(rb3p2);
        rb3p2.setText("156");

        bg2.add(rb4p2);
        rb4p2.setText("202");

        btnregresar2.setBackground(new java.awt.Color(0, 0, 0));
        btnregresar2.setForeground(new java.awt.Color(255, 255, 255));
        btnregresar2.setText("<<  REGRESAR");
        btnregresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar2ActionPerformed(evt);
            }
        });

        btnsiguiente2.setBackground(new java.awt.Color(0, 0, 0));
        btnsiguiente2.setForeground(new java.awt.Color(255, 255, 255));
        btnsiguiente2.setText("SIGUIENTE   >>");
        btnsiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguiente2ActionPerformed(evt);
            }
        });

        jLabel2.setText("2.  ¿Cuanto es 182 +20?");

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CUESTIONARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnregresar2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb1p2)
                                .addGap(18, 18, 18)
                                .addComponent(rb2p2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rb3p2)
                                .addGap(18, 18, 18)
                                .addComponent(rb4p2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(btnsiguiente2)
                                .addGap(57, 57, 57))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1p2)
                    .addComponent(rb2p2)
                    .addComponent(rb3p2)
                    .addComponent(rb4p2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregresar2)
                    .addComponent(btnsiguiente2))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb1p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1p2ActionPerformed

    private void btnsiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguiente2ActionPerformed
        // TODO add your handling code here:
        if (rb4p2.isSelected()){
            Resultado.puntos = Resultado.puntos + 20; 
        }
        setVisible(false);
        new JF3().setVisible(true);
    }//GEN-LAST:event_btnsiguiente2ActionPerformed

    private void btnregresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar2ActionPerformed
        // TODO add your handling code here:
         
        bg2.clearSelection();
           
        setVisible(false);
        new JF1().setVisible(true);
    }//GEN-LAST:event_btnregresar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg2;
    private javax.swing.JButton btnregresar2;
    private javax.swing.JButton btnsiguiente2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rb1p2;
    private javax.swing.JRadioButton rb2p2;
    private javax.swing.JRadioButton rb3p2;
    private javax.swing.JRadioButton rb4p2;
    // End of variables declaration//GEN-END:variables
}
