/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g4s21e4bfrb;

import Preguntas.Resultado;
/**
 *
 * @author Brayan Rodriguez
 */
public class JF3 extends javax.swing.JFrame {

    /**
     * Creates new form JF3
     */
    public JF3() {
        initComponents();
         bg3.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg3 = new javax.swing.ButtonGroup();
        rb1p3 = new javax.swing.JRadioButton();
        rb2p3 = new javax.swing.JRadioButton();
        rb3p3 = new javax.swing.JRadioButton();
        rb4p3 = new javax.swing.JRadioButton();
        btnregresar3 = new javax.swing.JButton();
        btnsiguiente3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg3.add(rb1p3);
        rb1p3.setText("321");
        rb1p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1p3ActionPerformed(evt);
            }
        });

        bg3.add(rb2p3);
        rb2p3.setText("1800");

        bg3.add(rb3p3);
        rb3p3.setText("180");

        bg3.add(rb4p3);
        rb4p3.setText("5390");

        btnregresar3.setBackground(new java.awt.Color(0, 0, 0));
        btnregresar3.setForeground(new java.awt.Color(255, 255, 255));
        btnregresar3.setText("<<  REGRESAR");
        btnregresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar3ActionPerformed(evt);
            }
        });

        btnsiguiente3.setBackground(new java.awt.Color(0, 0, 0));
        btnsiguiente3.setForeground(new java.awt.Color(255, 255, 255));
        btnsiguiente3.setText("SIGUIENTE   >>");
        btnsiguiente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguiente3ActionPerformed(evt);
            }
        });

        jLabel2.setText("3.   ¿Cuanto es 18 X 100?");

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CUESTIONARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnregresar3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb1p3)
                                .addGap(18, 18, 18)
                                .addComponent(rb2p3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rb3p3)
                                .addGap(18, 18, 18)
                                .addComponent(rb4p3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(btnsiguiente3)
                                .addGap(57, 57, 57))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1p3)
                    .addComponent(rb2p3)
                    .addComponent(rb3p3)
                    .addComponent(rb4p3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregresar3)
                    .addComponent(btnsiguiente3))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb1p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1p3ActionPerformed

    private void btnsiguiente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguiente3ActionPerformed
        // TODO add your handling code here:
        if (rb2p3.isSelected()){
            Resultado.puntos = Resultado.puntos + 20; 
        }
        setVisible(false);
        new JF4().setVisible(true);
    }//GEN-LAST:event_btnsiguiente3ActionPerformed

    private void btnregresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar3ActionPerformed
        // TODO add your handling code here:
      
         bg3.clearSelection();
           
        setVisible(false);
        new JF2().setVisible(true);
    }//GEN-LAST:event_btnregresar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg3;
    private javax.swing.JButton btnregresar3;
    private javax.swing.JButton btnsiguiente3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rb1p3;
    private javax.swing.JRadioButton rb2p3;
    private javax.swing.JRadioButton rb3p3;
    private javax.swing.JRadioButton rb4p3;
    // End of variables declaration//GEN-END:variables
}
