/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g4s21e4bfrb;

import Preguntas.Resultado;
/**
 *
 * @author Brayan Rodriguez
 */
public class JF4 extends javax.swing.JFrame {

    /**
     * Creates new form JF4
     */
    public JF4() {
        initComponents();
         bg4.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg4 = new javax.swing.ButtonGroup();
        rb1p4 = new javax.swing.JRadioButton();
        rb2p4 = new javax.swing.JRadioButton();
        rb3p4 = new javax.swing.JRadioButton();
        rb4p4 = new javax.swing.JRadioButton();
        btnregresar4 = new javax.swing.JButton();
        btnsiguiente4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg4.add(rb1p4);
        rb1p4.setText("1039");
        rb1p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1p4ActionPerformed(evt);
            }
        });

        bg4.add(rb2p4);
        rb2p4.setText("1263");

        bg4.add(rb3p4);
        rb3p4.setText("1243");

        bg4.add(rb4p4);
        rb4p4.setText("1123");

        btnregresar4.setBackground(new java.awt.Color(0, 0, 0));
        btnregresar4.setForeground(new java.awt.Color(255, 255, 255));
        btnregresar4.setText("<<  REGRESAR");
        btnregresar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar4ActionPerformed(evt);
            }
        });

        btnsiguiente4.setBackground(new java.awt.Color(0, 0, 0));
        btnsiguiente4.setForeground(new java.awt.Color(255, 255, 255));
        btnsiguiente4.setText("SIGUIENTE   >>");
        btnsiguiente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguiente4ActionPerformed(evt);
            }
        });

        jLabel2.setText("¿Cuanto es 1239 - 200");

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CUESTIONARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnregresar4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb1p4)
                                .addGap(18, 18, 18)
                                .addComponent(rb2p4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rb3p4)
                                .addGap(18, 18, 18)
                                .addComponent(rb4p4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(btnsiguiente4)
                                .addGap(57, 57, 57))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1p4)
                    .addComponent(rb2p4)
                    .addComponent(rb3p4)
                    .addComponent(rb4p4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregresar4)
                    .addComponent(btnsiguiente4))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb1p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1p4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1p4ActionPerformed

    private void btnsiguiente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguiente4ActionPerformed
        // TODO add your handling code here:
        if (rb1p4.isSelected()){
          Resultado.puntos = Resultado.puntos + 20;
           } 
        setVisible(false);
        new JF5().setVisible(true);
    }//GEN-LAST:event_btnsiguiente4ActionPerformed

    private void btnregresar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar4ActionPerformed
        // TODO add your handling code here:
        
           bg4.clearSelection();
           
        setVisible(false);
        new JF3().setVisible(true);
    }//GEN-LAST:event_btnregresar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg4;
    private javax.swing.JButton btnregresar4;
    private javax.swing.JButton btnsiguiente4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rb1p4;
    private javax.swing.JRadioButton rb2p4;
    private javax.swing.JRadioButton rb3p4;
    private javax.swing.JRadioButton rb4p4;
    // End of variables declaration//GEN-END:variables
}
