/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g4s21e4bfrb;

import Preguntas.Resultado;
/**
 *
 * @author Brayan Rodriguez
 */
public class JF5 extends javax.swing.JFrame {

    /**
     * Creates new form JF5
     */
    public JF5() {
        initComponents();
         bg5.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg5 = new javax.swing.ButtonGroup();
        rb1p5 = new javax.swing.JRadioButton();
        rb2p5 = new javax.swing.JRadioButton();
        rb3p5 = new javax.swing.JRadioButton();
        rb4p5 = new javax.swing.JRadioButton();
        btnregresar5 = new javax.swing.JButton();
        btnterminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblr = new javax.swing.JLabel();
        btnenviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg5.add(rb1p5);
        rb1p5.setText("20");
        rb1p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1p5ActionPerformed(evt);
            }
        });

        bg5.add(rb2p5);
        rb2p5.setText("1");

        bg5.add(rb3p5);
        rb3p5.setText("50");

        bg5.add(rb4p5);
        rb4p5.setText("10");
        rb4p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4p5ActionPerformed(evt);
            }
        });

        btnregresar5.setBackground(new java.awt.Color(0, 0, 0));
        btnregresar5.setForeground(new java.awt.Color(255, 255, 255));
        btnregresar5.setText("<<  REGRESAR");
        btnregresar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar5ActionPerformed(evt);
            }
        });

        btnterminar.setBackground(new java.awt.Color(0, 0, 0));
        btnterminar.setForeground(new java.awt.Color(255, 255, 255));
        btnterminar.setText("TERMINAR");
        btnterminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnterminarActionPerformed(evt);
            }
        });

        jLabel2.setText("5.   ¿Cuanto es 1000 / 100?");

        btnenviar.setBackground(new java.awt.Color(0, 0, 0));
        btnenviar.setForeground(new java.awt.Color(255, 255, 255));
        btnenviar.setText("Enviar");
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CUESTIONARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnterminar)
                        .addGap(68, 68, 68))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblr, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(rb1p5)
                                .addGap(18, 18, 18)
                                .addComponent(rb2p5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb3p5)
                                .addGap(18, 18, 18)
                                .addComponent(rb4p5))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnregresar5)
                                .addGap(89, 89, 89)
                                .addComponent(btnenviar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1p5)
                    .addComponent(rb2p5)
                    .addComponent(rb3p5)
                    .addComponent(rb4p5))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregresar5)
                    .addComponent(btnenviar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnterminar)
                .addGap(32, 32, 32)
                .addComponent(lblr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb1p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1p5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rb1p5ActionPerformed

    private void btnterminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnterminarActionPerformed
        // TODO add your handling code here:
        lblr.setText("El resultado es " + Resultado.puntos );
        
    }//GEN-LAST:event_btnterminarActionPerformed

    private void btnregresar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar5ActionPerformed
        // TODO add your handling code here:    
        setVisible(false);
        new JF4().setVisible(true);
        bg5.clearSelection();
    }//GEN-LAST:event_btnregresar5ActionPerformed

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        // TODO add your handling code here:
        if (rb4p5.isSelected()){
          Resultado.puntos = Resultado.puntos + 20;
           } 
    }//GEN-LAST:event_btnenviarActionPerformed

    private void rb4p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4p5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb4p5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg5;
    private javax.swing.JButton btnenviar;
    private javax.swing.JButton btnregresar5;
    private javax.swing.JButton btnterminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblr;
    private javax.swing.JRadioButton rb1p5;
    private javax.swing.JRadioButton rb2p5;
    private javax.swing.JRadioButton rb3p5;
    private javax.swing.JRadioButton rb4p5;
    // End of variables declaration//GEN-END:variables
}
